# Generated by Django 5.0.2 on 2024-07-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_contact_user_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='username',
        ),
    ]
