# Generated by Django 5.0.2 on 2024-05-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_membership_status_user_alter_payment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_of_birth',
        ),
    ]
