# Generated by Django 5.0.2 on 2024-05-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_muscle_submuscle_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='muscle',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
