# Generated by Django 5.0.2 on 2024-05-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_exercise_sub_muscle_alter_muscle_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
